server:
  port: 6666
spring:
  #security:
  # user:
  #   name: admin
  #  password: a
  # roles:
  #  - USER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wgf123lxl
    url: jdbc:mysql://123.57.20.138:3306/db_ifav?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  application:
    name: ifav-provider-reg  #应用服务名
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc.ifav: debug

eureka:
  client:
    service-url:
      defaultZone: http://admin:a@localhost:7301/eureka
  instance:
    instance-id: ifav-provider-tag_1   #实例名
    lease-expiration-duration-in-seconds: 90  #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )


#监控配置
info:
  app.name: MICROSERVICE-IFAV
  company.name: yc
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: '*'